apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.tkestack.io
spec:
  group: etcd.tkestack.io
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    plural: etcdclusters
    singular: etcdcluster
    shortNames:
      - etcd
  preserveUnknownFields: true
  scope: Namespaced
  subresources:
    status: { }
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
