{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tapp.serviceAccountName" . }}
#  namespace: {{ .Release.Namespace }}
  namespace: kube-system
  labels:
    {{- include "tapp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tapp.serviceAccountName" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "tapp.serviceAccountName" . }}
#    namespace: {{ .Release.Namespace }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
