apiVersion: v1
kind: Service
metadata:
#  name: {{ include "tapp.fullname" . }}
  name: tapp-controller
  labels:
    {{- include "tapp.labels" . | nindent 4 }}
  namespace: kube-system
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
  selector:
    {{- include "tapp.selectorLabels" . | nindent 4 }}
