apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [auth.anonymous]
    enabled=true
    [security]
    allow_embedding = true
    [server]
    root_url = http://localhost/grafana/
    serve_from_sub_path = true
kind: ConfigMap
metadata:
  name: grafana
---
apiVersion: v1
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
     - name: KSTONE-PROM
       type: prometheus
       access: proxy
       orgId: 1
       url: http://{{ .Release.Name }}-prometheus-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
       isDefault: true
       editable: false
kind: ConfigMap
metadata:
  labels:
    grafana/datasource: default
  name: grafana-default-datasource
---
apiVersion: v1
data:
{{ (.Files.Glob "dashboards/*").AsConfig | indent 2 }}
kind: ConfigMap
metadata:
  labels:
    grafana/dashboards: default
  name: grafana-etcd-dashboards
---
apiVersion: v1
data:
  dashboard.yaml: |-
    apiVersion: 1
    providers:
      - name: 'dasboard'
        type: file
        disableDeletion: true
        editable: true
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /etc/grafana/dashboards
          foldersFromFilesStructure: false
kind: ConfigMap
metadata:
  name: grafana-dashboard-import